<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZifa6yz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZifa6yz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZifa6yz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZifa6yz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZifa6yz\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zifa6yz',
    'container.build_id' => '4ef2da46',
    'container.build_time' => 1519315985,
));
