<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8waqc7t\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8waqc7t/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8waqc7t.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8waqc7t\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8waqc7t\appDevDebugProjectContainer(array(
    'container.build_hash' => '8waqc7t',
    'container.build_id' => '984b535b',
    'container.build_time' => 1519396558,
));
